image:
    name: registry.samcollier.dev/samcollier/wii-zig

stages:
  - build
  - test

build_wii_ppc:
  stage: build
  script:
    - zig build
  artifacts:
    when: always
    paths:
      - ./zig-out/*
      - ./.zig-cache/*

test_wii_ppc:
  stage: test
  needs:
    - job: build_wii_ppc
      artifacts: true
  script:
    - zig build test-junit
  artifacts:
    when: always
    reports:
      junit: zig-out/test-results.xml
