image:
    name: registry.samcollier.dev/samcollier/wii-zig

stages:
  - build
  - test

build_wii_ppc:
  stage: build
  script:
    - zig build
  artifacts:
    when: always
    paths:
      - ./zig-out/*
      - ./.zig-cache/*

test_wii_ppc:
  stage: test
  needs:
    - job: build_wii_ppc
      artifacts: true
  script:
    - echo "HOME=$HOME"
    - echo "USER=$(whoami)"
    - cat $HOME/.config/dolphin-emu/Dolphin.ini || echo "NO CONFIG FOUND"
    - dolphin-emu-nogui -v Null -p headless zig-out/wii-zig.dol || true
    - zig build test-junit
  artifacts:
    when: always
    reports:
      junit: zig-out/test-results.xml
